# Generated by Django 5.2 on 2025-07-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(max_length=13, verbose_name="estado del artículo"),
                ),
                ("categoria", models.CharField(max_length=20)),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
    ]
