# Generated by Django 5.2.4 on 2025-07-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('estado_fisico', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Excelente', 'Excelente estado'), ('Buen', 'Buen estado'), ('Regular', 'Regular'), ('Desgastado', 'Desgastado')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('prestamo_max_dias', models.PositiveSmallIntegerField()),
                ('plazo_max_dias', models.PositiveSmallIntegerField()),
                ('ubicacion', models.CharField(max_length=80)),
                ('horario_inicio', models.TimeField(default='08:00:00')),
                ('horario_fin', models.TimeField(default='20:00:00')),
                ('imagen', models.ImageField(upload_to='articulos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulo.categoria')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
