# Generated by Django 5.2 on 2025-07-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="nombre",
            field=models.CharField(default="Artículo sin nombre", max_length=30),
            preserve_default=False,
        ),
    ]
