# Generated by Django 5.2 on 2025-07-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0002_articulo_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="descripcion",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
