# Generated by Django 4.2.23 on 2025-07-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0003_alter_articulo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
