# Generated by Django 5.2 on 2025-07-11 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articulo", "0003_alter_articulo_descripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bloqueo",
            fields=[
                (
                    "accion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accion.accion",
                    ),
                ),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("motivo", models.TextField()),
            ],
            bases=("accion.accion",),
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "accion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accion.accion",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(verbose_name="Fecha de vencimiento"),
                ),
                (
                    "id_articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="articulo.articulo",
                    ),
                ),
            ],
            bases=("accion.accion",),
        ),
        migrations.CreateModel(
            name="Devolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_devolucion",
                    models.DateTimeField(verbose_name="Fecha de devolución"),
                ),
                (
                    "id_reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="accion.reserva"
                    ),
                ),
            ],
        ),
    ]
